# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               NullZero
tagline:             'A virtual bitbucket of ramblings about technology.'
description:         'A virtual bitbucket of ramblings about technology.'
url:                 http://www.nullzero.io
baseurl:             ''
paginate:            5
highlighter: true

# About/contact
author:
  name:              Kevin Kirkpatrick
  url:               https://twitter.com/vscripter
  email:             kevin@nullzero.io

# Custom vars
version:             1.0.0
